### PR TITLE
Configure machine user

### PR DESCRIPTION
**Pull request by neomatrix369**
DO NOT MERGE till PR #23 is merged

This PR is on the back of the discussion about making the machine user and the associated email address to it, configurable for the user.

CircleCI environment config will require a change, **we will need to rename METERIAN_GITHUB_TOKEN to METERIAN_MACHINE_USER_TOKEN**, builds will break otherwise.

Also, the value assigned to _METERIAN_MACHINE_USER_TOKEN_ will need to be that from the _METERIAN_MACHINE_USER_ and not from any other account.

### CODE REVIEW

**Comment by neomatrix369** [comment]
> So we need to be clear about what these variables are about, so, as also for #23, we should prefix with GITHUB what pertains to GITHUB. So, specifically:
> METERIAN_MACHINE_USER -> GITHUB_USER
> METERIAN_MACHINE_USER_EMAIL` -> GITHUB_EMAIL
> while
> METERIAN_GITHUB_TOKEN -> GITHUB_TOKEN
> 
> This also needs to be reflected in the code. it's of course okay mention the concept of "machine users" in the documentation, but the variable names should be changed.

I have responded to the naming of this on #23, same response here. 

Calling the name what is contains and meant to do helps in conveying the message on how to configure and use the plugin, changing the name will take away that clarity. I'm seeing this from the user perspective.

**Comment by neomatrix369** [comment]
I'll resolve the merge conflict as it must have occurred due to merging of pervious branches.

**Comment by neomatrix369** [comment]
> Let's discuss this one, I am not sure what it's meant to achieve.

This allows the end user to configure the plugin to use their own machine user and not `meterian-bot` like we have done in our previous changes so far.

By default it will switch back to `meterian-bot` if they don't set it. It came out of our discussions previously. 

Unless you would like this to be `meterian-bot` explicitly?

**Comment by neomatrix369** [comment]
Rebase done, although PR will fail unless we do the above and also resolve our discussions above.

**Comment by bbossola** [comment]
These are the variables on CircleCI atm:

Screenshot from 2019-06-17 15:57:18

We assume GITHUB_TOKEN is deprecated and we will remove it when this is merged.

**Comment by neomatrix369** [comment]
@bbossola this PR is good to go!

**Comment by neomatrix369** [comment]
Please remove GITHUB_TOKEN from CircleCI once this PR is merged

**Pull request merged**
